### ISSUE TITLE
Installation in a Gulpfile

### ISSUE THREAD

**Issue by skube** [michalsnik/aos#181]
Wondering if there are any installation docs when using a Gulpfile?

I've found the only way to get the styles is `@import` them in my `main.scss` file by:

`@import '../../node_modules/aos/src/sass/aos.scss';`

**Comment by michalsnik** [comment]
It's a regular `npm` and `bower` package and you can install it however you like. You can either add regular `<link>` to those styles using CDN or installed package. Or import as you mentioned above.
You could probably also pipe this together with your styles and concat it later using `gulp-concat` plugin:
```
gulp.src([
  './node_modules/aos/dist/aos.css',
  'your-styles.css'
])
.pipe(concat('all.css'))
```

The best way however is to import those styles in your `scss` file, so that you can override default variables when you need, but you'll need to handle autoprefixing on your own.
