### ISSUE TITLE
AJAX loaded items not fading

### ISSUE THREAD

**Issue by nathanaelphilip** [michalsnik/aos#22]
Is there a special trick to handle content that is lazy loaded? I tried firing AOS.refresh(), but that doesn’t seem to help very much.

Thanks again :)

**Comment by michalsnik** [comment]
Hi again @nathanaelphilip. `refresh()` is a pretty light function - it only check position of elements that were found during initialization. And it's called whenever `aos` element is being injected to DOM because of the DOM observer implementation.

Ouch.. Now I see what I did wrong there. I should add another method, for example `hardRefresh` - which will not only recalculate and check positions of elements, but also mutate the store with those elements by pushing new items.

I'm definitely going to make it work.

For now as a quick workaround you can instead of `refresh` use `init` with the same options. It should work well I guess ;)

**Comment by nathanaelphilip** [comment]
sweet! i’ll try that for now. thanks :). this plugin is really nice and i think will replace my own custom way (once all the bugs are worked out).

**Comment by michalsnik** [comment]
Glad to hear that :) Stay tuned

**Comment by ErtugKaya** [comment]
I'd add a parameter to `refresh` instead of introducing a new method. For instance `refresh(checkDOMs)` will reduce confusion.

If you want to go further, there is an API called [_MutationObserver_](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) for detecting DOM changes. Maybe you can hook it and do an auto refresh when a DOM is added or hook it, flag when a change is detected and recheck DOMs only when `refresh` is called manually. By this you will have an intelligent method that knows if to check DOMs or not. Putting an _auto refresh when DOM change_ in the options will complete this.

Check this out: [http://stackoverflow.com/questions/3219758/detect-changes-in-the-dom](http://stackoverflow.com/questions/3219758/detect-changes-in-the-dom)

**Comment by michalsnik** [comment]
MutationObserver is actually implemented @ErtugKaya ;) I use it to detect DOM changes and trigger reload. But I spot an issue after @nathanaelphilip message that reload is not checking position of new elements, only the initial ones. I'm going to fix this soon.

I'd rather avoid messing with parameters. Another private method that prepares fresh store with elements and reuses actual `reload` would be IMHO the cleanest and proper solution.

I'll let you know when it's done in this topic.

**Comment by michalsnik** [comment]
Hi, I just fixed this issue in #24 .
Version `1.2.2` works like expected.
Now whenever you load some items using ajax they automatically animate and behave properly.

Hope you find this useful :)
