### ISSUE TITLE
How to do server rendering ?

### ISSUE THREAD

**Issue by ferhatelmas** [michalsnik/aos#236]
Since package requires existence of `window` and `document`, it will fail while importing.

**Comment by OscarGalindo** [comment]
i'm having this issue just now, any thoughts?

**Comment by elvisguillen** [comment]
I'm having this issue as well, getting a 'Window is not defined' error when doing server rendering with React. I have found no solutions so far.

**Comment by bfan1256** [comment]
There is a method of using [rendertron](http://render-tron.appspot.com/) where you can server-side render for bots to crawl your website and then send your regular react to a client. I'm not a react developer, but you can attempt to check if the window variable is defined.

**Comment by PaulVCS** [comment]
if you have a componentDidMount you could just create a aos component and in the componentDidMount do a simple check to see if it's already started or not.

`  componentDidMount(){
    if(AOS.refresh() === undefined){
      AOS.init(); 
    }
  }`

**Comment by michalsnik** [comment]
Hey, have you tried updating initialization?
```js
if (window) {
  AOS.init();
}
```
Once I set SSR locally I'll be able to also confirm and provide with decent solution. Currently I'm just guessing.

**Comment by PaulVCS** [comment]
Yes that should also work, you can setup a server-side rendering by using [nextjs](https://nextjs.org/) it's the quickest way to get started just for testing this, but like I said you will have to do the check once the component has mounted, I will do a check what happens if you do it outside of the componentDidMount, but anyway this is not a problem with AOS it's simply how the virtual dom works, so unless AOS gets converted into a webpacked react module component this will persist. I see that @dbramwel has already done this as seen here [React-Animate-on-Scroll](https://github.com/dbramwell/react-animate-on-scroll/blob/master/src/scroll-animation.js)

**Comment by michalsnik** [comment]
AOS does no longer have browser related instances in global scope. Please try `2.3.1` that I just released :) And feel free to reopen if you'll experience further issues.
