### ISSUE TITLE
Image set as fixed and slide-in/slide-out effect

### ISSUE THREAD

**Issue by dawidtokarz** [michalsnik/aos#247]
Hi guys,

I'm using AOS script in one of my projects and it works like a charm, but I have some problem with one element. There is an image set as position fixed in the bottom of a page. Is it possible to gain slide-in/slide-out (fade-up/down) effect with AOS on fixed element?

**Comment by mizukimadness** [comment]
I wonder the same thing.

**Comment by singhv18** [comment]
The `position:fixed;` element just fades in for some reason, even if I have `fade-left` or `fade-right` set. Any solution to it?

**Comment by michalsnik** [comment]
Hey @dawidtokarz It is possible, but if the element is fixed - it doesn't change it's position regarding window so if you want to trigger an animation on it - you should use `data-aos-anchor` option and set selector to other element, which position you want to trigger the desired animation on fixed element. Does it make sense?

You can see fixed elements being animated here: https://codepen.io/michalsnik/pen/jrOYVO

Feel free to reopen this issue if your problem is somewhat different than I assumed :)
