### ISSUE TITLE
Consider binding to event listener to window instead of document for initilization

### ISSUE THREAD

**Issue by nathanaelphilip** [michalsnik/aos#26]
`https://developer.mozilla.org/en-US/docs/Web/Events/load`

I’m not getting an init when setting the `options.startEvent` to `load`. The documentation above suggests binding load to `window` instead of `document`. Is that something you think would be better? Maybe just check for `load` and use `window` instead of `document`. 

I’m more than happy to do a pull request, but it’s just one line :)

The main issue I’m having, is that when I have any elements in the top area, they’re not animating in – they just sit there.

**Comment by michalsnik** [comment]
Hi,

I intentionally listen for events on document. However I'll consider your proposal with listening on `window` when event is `load`.

But the problem you encountered is caused probably by `data-aos` attributes. If you use `aos` attributes it should animate fine. It's because AOS changes all `data-aos` attributes to `aos` on the fly, and it causes lack of animation on elements that are already in viewport.

Currently I'm working on version `2.0.0` where I'm going to remove `aos` attributes and leave only `data-aos`. So the only working solution would be the correct one. And there will be no animations issues like this anymore. If you're interested what's going on in `2.0.0` check #25 and feel free to add your thoughts. I'd be happy to discuss.

For now you can change `data-aos` to `aos` and see if this helps.

**Comment by nathanaelphilip** [comment]
perfect, thank you!

**Comment by nathanaelphilip** [comment]
remove `data-` works perfectly. thank you :)

**Comment by michalsnik** [comment]
Hi, I just updated AOS. Now when you set `startEvent: 'load'` it will automatically add event listener on `window` instead of `document`. Since version `>= 2.1.0`
