### ISSUE TITLE
Not triggering correctly

### ISSUE THREAD

**Issue by anetk** [michalsnik/aos#34]
Hello,
can anyone take a look at my aos animation and see why they dont trigger right?
third section with iphone messages popping up --
so they should go one by one but not doing it even with delays and when i scroll up i want it to do it again

**Comment by michalsnik** [comment]
Hi @anetk 

First of all try to use newset version, which is `2.0.4`:

```
<link href="https://cdn.rawgit.com/michalsnik/aos/2.0.4/dist/aos.css">
```

```
<script src="https://cdn.rawgit.com/michalsnik/aos/2.0.4/dist/aos.js">
```

Then make sure you use `data-aos*` attributes everywhere (These are the only proper ones since `2.0.0`).

You don't have to override delay in your styles. By default there are durations and delays generated from 0 to 3000 with step 50.

Make sure you have `AOS.init()` in your JavaScript, and when it's still not working, try to add:

```
$(window).on('load', function () {
    AOS.refresh();
});
```

**Comment by anetk** [comment]
Thanks a lot for quick response(:  New version worked just perfectly!!Thank you!!

**Comment by michalsnik** [comment]
Glad to hear that :)

**Comment by Marinnnnce8** [comment]
Tnx, that works for me! :)

**Comment by sandipkaushik** [comment]
new version not working

**Comment by danielalvares** [comment]
@sandipkaushik try to use the following:

`$(window).load(function() {
    setTimeout(function() {
        AOS.refresh();
    }, 500);
});`

For me, at least it worked. I'm not sure why the script has a delay sometimes, but this can handle the problem. I Hope it can helps you.

**Comment by Obewong** [comment]
I also found if you are still having issues, put a global delay to your animations for eg...

       AOS.init({ 
            duration: 700,
            delay: 400,
            once: true,
        });

**Comment by rahuljha12527** [comment]
HI I make custom animation i am using data aos but not working @michalsnik
