### ISSUE TITLE
AOS disable function only works conditionally

### ISSUE THREAD

**Issue by Leartech-Studios** [michalsnik/aos#355]
Disable function will only work on page load, not afterwards. Is there a way around this? would be a great way to implement responsive pages that change whe the user resizes the window. Thanks.

**Comment by michalsnik** [comment]
@Leartech-Studios I don't see any workaround unfortunately.

Why would this be applied on browser resize? Users usually open page either on mobile or desktops and AOS will either work, or be disabled. I don't see real value in allowing users to resize window to mobile size in order to automatically disable AOS for them. Current behaviour is intentional. If you however have some valid arguments that say otherwise, I'm happy to hear them out :)
