### ISSUE TITLE
3.0.0 Stable Release

### ISSUE THREAD

**Issue by simmonsr** [michalsnik/aos#363]
When do you plan on releasing stable version of 3.0.0?

**Comment by michalsnik** [comment]
In the next 2 weeks it should be out :) I need to make sure it's stable

**Comment by simmonsr** [comment]
okie thx

**Comment by ktmn** [comment]
Is it stable now?

**Comment by simmonsr** [comment]
Not quite, but the beta 4 is a solid beta:

https://github.com/michalsnik/aos/releases

**Comment by dlewand691** [comment]
What is the differences between v2 and v3? Are there any limitations or risks of upgrading to aos-next beta 6?

**Comment by dgobnto** [comment]
> When do you plan on releasing stable version of 3.0.0?

It's been 2 years now since the original question (@simmonsr) and no 3.0.0 stable release… Is this project on halt? Are there any plans of actually releasing a stable version? How safe is it to use beta 6 on a production site?
> What is the differences between v2 and v3? Are there any limitations or risks of upgrading to aos-next beta 6?

I'm also (@dlewand691) not quite sure what the differences are between v2 and v3. Any hints, please?
