### ISSUE TITLE
'disable' property doesn't work

### ISSUE THREAD

**Issue by VadimZP** [michalsnik/aos#374]
I want to disable animation on mobiles but 'disable' property doesn't work. What's the problem?

` AOS.init({
        disable: 'mobile',
        delay: 0,
        once: true,
});`

**Comment by ramen-mukherjee** [comment]
I am also facing the same issue. In resizable mode, I need the animation to happen in desktop, not happen in below desktop scenario and happen once again when user resizes back to desktop WITHOUT reloading the page. AOS.init({disable: false}), .refresh(), .refreshHard() not working.

**Comment by simmonsr** [comment]
@VadimZP how about disable: 'phone' ?

**Comment by moonbyt3** [comment]
ok it turns out it DOES work :) thank you 👍

**Comment by michalsnik** [comment]
If you need more flexibility you can write your own animation @ramen-mukherjee and use media queries inside of them to tell exactly how the element should behave on what resolution.
Due to performance reasons I'm not going to enable/disable AOS on page resize event - only on page refresh, because this is the normal scenario - your users won't change the browser from phone resolution to desktop all of the sudden.
