### ISSUE TITLE
AOS not working on parallax scrolling 

### ISSUE THREAD

**Issue by MaybeRex** [michalsnik/aos#376]
## This is:
- Question

## Specifications

  - AOS version: 2.3.1
  - OS: Windows 10 pro/Mac OS high sierra
  - Browser: chrome 

## Expected Behavior
AOS fade in should work on scroll

## Actual Behavior
Nothing happens on scroll
fade in happens on resize (open the console tab on codepen to simulate this)

## Steps to Reproduce the Problem
1. add `data-aos="fade-up` 
2. observe nothing happens 
## Detailed Description
Open the codepen above, observe that the `<div class="Content" data-aos="fade-up">`
element does not show, if one removes the data-aos, it shows correctly

**Comment by MaybeRex** [comment]
adding 
`document.body.querySelector('.MainContainer').addEventListener('scroll', AOS.init);`
fixed the issue but is inefficient

**Comment by johnboker** [comment]
I have the same problem, a fix that seems to work for me, since im already using jQuery was to delay the call of AOS.init() a bit while the other libraries did their thing:

```
<script>
  jQuery(document).ready(function(){
    setTimeout(AOS.init, 500);
  });
</script>
```

**Comment by michalsnik** [comment]
Please don't initialize AOS multiple times, It might result in a giant leak and serious slowdown.
AOS unfortunately doesn't have the `container` scroll support yet, but you might `hack` it and do something similar to what you already did @MaybeRex but using `refresh` instead of `init`:
```
document.body.querySelector('.MainContainer').addEventListener('scroll', AOS.refresh);
```
But you might also want to add `throttle` to not spam your browser with bunch of those actions to keep your page performant.
