### ISSUE TITLE
Custom Scrollbar scruypt vs AOS

### ISSUE THREAD

**Issue by bodanus7** [michalsnik/aos#399]
- Question

Hello,
Can anyone help me with integration of AOS library to work together with Smooth-Scrollbar (https://github.com/idiotWu/smooth-scrollbar)?
The problem is they are listen to window resize events, when they change.
The smooth-scrollbar doesn't trigger the resize events.

Thank you in advance,
Bodanus

**Comment by michalsnik** [comment]
Unfortunately this will not be possible. Smooth-scrollbar translates the whole container to provide the smooth animation and this messes up our calculations of elements' positions. Sorry @bodanus7 but I'm not going to address this.

**Comment by oguilleux** [comment]
@bodanus7 here is a script that works for everything except data-aos-offset :
```
const myScrollbar = Scrollbar.init(document.querySelector('.site__wrapper'));

[].forEach.call(document.querySelectorAll('[data-aos]'), (el) => {
  myScrollbar.addListener(() => {
    if (myScrollbar.isVisible(el)) {
      el.classList.add('aos-animate');
    }
  });
});

```

I'm sure there is a way to use offset in this function.

**Comment by techvsi-datho** [comment]
Other way if you want it's run better at other position. Instead of use check isVisible of smooth scrollbar. Because the function of smooth scrollbar will be run when component reach bottom browser device.

These is a simple I did:
Lib: 
- [Smooth Scrollbar JS](https://idiotwu.github.io/smooth-scrollbar/)
- [GSAP](https://gsap.com/) + [SCrollTrigger](https://gsap.com/docs/v3/Plugins/ScrollTrigger/)
- [AOS](https://michalsnik.github.io/aos/)

I used gsap because i got some other animation need to use that package.
```
import gsap from "gsap";
    import { ScrollTrigger } from "gsap/ScrollTrigger";
    import AOS from 'aos';
    import 'aos/dist/aos.css';

  /*Register Scroll Trigger*/
   gsap.registerPlugin(ScrollTrigger)

/*Init Smooth SCroll*/
   const smoothScroll = Scrollbar.init(scroller, { damping: 0.05, delegateTo: document, alwaysShowTracks: false })
   let getAllAos = Array.prototype.slice.call(document.querySelectorAll('[data-aos]'))

/*Implement SCrollTrigger With SmoothSCroll*/
   ScrollTrigger.scrollerProxy('#main-scrollbar', {
            scrollTop(value) {
                if (arguments.length) {
                    smoothScroll.scrollTop = value;
                }
                return smoothScroll.scrollTop;
            }
        });

       smoothScroll.addListener(ScrollTrigger.update);

        ScrollTrigger.defaults({ scroller: scroller });
        AOS.init()
        getAllAos.length > 0 && getAllAos.forEach((item)=>{
            gsap.to(item,{
                scrollTrigger: {
                    trigger: item,
                    start: 'top center',
                    end: 'bottom center',
                    once:true,
                    onEnter:(scroll)=>{
                        item.classList.add('aos-animate');
                    }
                }
            })
        })
```

You can follow how to implement smooth scrollbar + scrollTrigger too: https://codepen.io/Daniel-Ho-the-animator/pen/ExGMVwX

Also Thank you @oguilleux , cause your code made me have this idea.
