### ISSUE TITLE
Real ES6 exports from source

### ISSUE THREAD

**Issue by tinovyatkin** [michalsnik/aos#62]
Great library, thank you!
As it written in ES6 I think it's just one step left to offer real ES6 `export` and use `jsnext:main` field in `package.json`: https://github.com/rollup/rollup/wiki/jsnext:main - it will result in very handy imports for other ES6 apps.

**Comment by michalsnik** [comment]
UMD works here pretty good I think. It can be used in any stack right now and was already used with success in React or Meteor using:
```
import AOS from 'aos';
```

I'm not taking advantage here of ES6 Modules, because what I want is to export whole plugin and not make it possible to import only specific parts - it's not that kind of library. So for purposes of this plugin - UMD seems like a good call - and it already works everywhere :)
