### ISSUE TITLE
Custom wordpress website element loading problem

### ISSUE THREAD

**Issue by ghost** [michalsnik/aos#716]
It is possible that the images featured with WordPress created a conflict with the library. The first image loads and when you scroll the page the other elements are already animated. While the goal is to scroll the page so the other elements of the page scroll in turn depending on the animation chosen

I found the solution for custom themes anyway on a local server it works:

The bug came from the images put forward by WordPress, for my part directly linked by a "Custom Post type"

If on your WordPress site you have a lazy load on your images, you must use this function in the file js aos:
`document.querySelectorAll('img') .forEach((img) => img.addEventListener('load', () => AOS.refresh() ) );`

Then it is possible that there is a bug by configuring the animations with:
`AOS.init({ once: true, // or false });`

Then it will be necessary to check if the dimensions of the images are indicated in the HTML. For my part in my functions.php I had put this

`function respon_image ( $html ) { $html = preg_replace( '/(width|height)="\d*"\s/', "", $html ); return $html; } add_filter( 'post_thumbnail_html', 'respon_image', 10 ); add_filter( 'image_send_to_editor', 'respon_image', 10 ); add_filter( 'wp_get_attachment_link', 'respon_image', 10 );`

This code allows you to remove the attributes of image dimensions highlighted by default by WordPress. So that the images are directly responsive

So remove this function and put in your CSS: `width: 100%` and `height 100%` or leave the default attributes given by WordPress.

**Comment by thierrydeve** [comment]
Finally, I found the solution for custom themes anyway on a local server it works:

The bug came from the images put forward by WordPress, for my part directly linked by a "Custom Post type"

If on your WordPress site you have a lazyload on your images, you must use this function in the file js aos:
`document.querySelectorAll('img')
    .forEach((img) =>
        img.addEventListener('load', () =>
            AOS.refresh()
        )
    );`

Then it is possible that there is a bug by configuring the animations with:
`AOS.init({
  once: true, // or false
});`

Then it will be necessary to check if the dimensions of the images are indicated in the html. For my part in my functions.php I had put this

`function respon_image ( $html ) {
$html = preg_replace( '/(width|height)="\d*"\s/', "", $html );
return $html;
}
add_filter( 'post_thumbnail_html', 'respon_image', 10 );
add_filter( 'image_send_to_editor', 'respon_image', 10 );
add_filter( 'wp_get_attachment_link', 'respon_image', 10 );`

This code allows you to remove the attributes of image dimensions highlighted by default by WordPress. So that the images are directly responsive

So remove this function and put in your css: width: 100% and height 100% or leave the default attributes given by WordPress.
