### ISSUE TITLE
If the script does not load, the elements stay hidden

### ISSUE THREAD

**Issue by sylvaindev** [michalsnik/aos#78]
Is it possible that the elements will not hide if the script is not loaded?

**Comment by abstractpenguin** [comment]
It looks like AOS will apply a .aos-init when it is loaded, so you could likely apply the initial hidden style to .element-to-animate.aos-init (much like the fine completed animation state is applied to .element-to-animate.aos-animate).

Here's an example from my SCSS:
`.row--plates {
  &.aos-init {
    opacity: 0;
    transition-property: transform, opacity;
    transform: scale(.6);
    transition-duration: 3s;
  }
  &.aos-animate {
      opacity: 1;
      transform: translate(0, 0) scale(1);
    }
  }
}`

**Comment by michalsnik** [comment]
Elements are being hidden right away in css @sylvaindev to not cause weird flashing of those elements. Otherwise they would appear for a second or so, then disappear and after that animate - which would look strange. If you need to show them on start I suggest you simply check AOS styles, and override them or write your own ;)
