### ISSUE TITLE
How to change animation using dropdown onchange event

### ISSUE THREAD

**Issue by nandlal-tjm** [michalsnik/aos#93]
Hi,
I am using user selected animation. When user change the animation from dropdown list, also animate the preview box. (as below image).
![preview](https://cloud.githubusercontent.com/assets/5101781/21987005/8f52cf16-dc23-11e6-9c4f-59a84da06d0f.png)

This is my code ;
`$( function() {
 		
 		$( '.animation-wrap' ).each( function() {
 			
	 		var $wrap = $(this);
	 		var preview = $wrap.find('.animation-preview');
	 		var dropdown = $wrap.find('.animation-dropdown ');

	 		dropdown.change( function() {
	 			var val = $(this).val();
	 			//preview.removeClass('aos-animate aos-init');
	 			//preview.removeData('aos', null);
	 			preview.attr('data-aos', val);
	 			AOS.init();
	 		});

		});

I play various ways but did not work.

**Comment by michalsnik** [comment]
Hey @nandlal-tjm , you could achieve it like this:
http://codepen.io/michalsnik/pen/apBKzx

It's not entirely clean solution, and I'd prefer a different one - you can replace `preview` node with new one with proper `data-aos` on `change`, then it's all you need to do because AOS will detect that there appeared new element in DOM and will call animation on this new node. So you won't have to set any classes and so on. I think this would be the best solution.

**Comment by michalsnik** [comment]
I'm closing this issue now. Feel free to reopen if you'll find some issues regarding AOS.
