### ISSUE TITLE
Animation fails w/ duration over 3000ms

### ISSUE THREAD

**Issue by bizdemon** [michalsnik/aos#97]
Hi there, I'd like to migrate from animate.css+wow to aos but seems animations fail with duration over 3000ms (and I'm using a lot of slow animations up to 7s).

Lucio

**Comment by WPsites** [comment]
See the homepage of this github repo where it says...



*Duration accept values from 50 to 3000, with step 50ms, it's because duration of animation is handled by css, and to not make css longer than it is already I created implementations only in this range. I think this should be good for almost all cases.

If not, you may write simple CSS on your page that will add another duration option value available, for example:

  body[data-aos-duration='4000'] [data-aos], [data-aos][data-aos][data-aos-duration='4000']{
    transition-duration: 4000ms;
  }
This code will add 4000ms duration available for you to set on AOS elements, or to set as global duration while initializing AOS script.

**Comment by michalsnik** [comment]
Thanks @WPsites for a quick response here
